# Generated by Django 2.1 on 2018-09-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180826_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='test', max_length=225, verbose_name='总结'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=True, verbose_name='是否隐藏'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, verbose_name='日期'),
        ),
    ]
